trigger:
  branches:
    include:
      - main

variables:
  ACR_LOGIN_SERVER: 'build68build68.azurecr.io'
  IMAGE_NAME: 'build68build68-user-service'
  IMAGE_TAG: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    jobs:
      - job: BuildPush
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - script: |
              echo "Copying pre-built JAR to Docker context..."
              mkdir -p docker
              cp services/user-service/target/*.jar docker/app.jar
            displayName: 'Prepare Docker Context'

          - task: Docker@2
            displayName: 'Build and Push Docker Image'
            inputs:
              command: buildAndPush
              containerRegistry: 'build68build68-acr-serviceconn' 
              repository: '$(IMAGE_NAME)'
              dockerfile: 'services/user-service/Dockerfile'
              buildContext: 'docker'
              tags: |
                $(IMAGE_TAG)
